#!/bin/sh
set -e
NAME=post-build-checks
VERSION=13.2
scmver=`git log -n1 --date=short --pretty=format:"$VERSION+git%cd.%h"|sed 's@-@@g'`
fullver="$scmver"
pfx="$NAME${fullver:+-$fullver}"
fn="$pfx".tar.xz
git archive --prefix="$pfx"/ HEAD | xz > $fn
echo "version $fullver -> $fn"
