#!/bin/sh
set -e
NAME=post-build-checks
VERSION=1.0
datefmt="%Y.%m.%d.%H%M"
LAST_COMMIT=(`git rev-list --timestamp HEAD^..HEAD`)
DATE=`date +$datefmt -d "1970-01-01 00:00 UTC $LAST_COMMIT seconds"`
#scmver="$DATE"
fullver="$VERSION${scmver:+_}$scmver"
pfx="$NAME${fullver:+-$fullver}"
fn="$pfx".tar.bz2
git archive --prefix="$pfx"/ HEAD | bzip2 > $fn
echo "version $fullver -> $fn"
