#!/bin/bash

echo "... installing all built rpms"
TOPDIR=/usr/src/packages
test -d $BUILD_ROOT/.build.packages && TOPDIR=/.build.packages
export YAST_IS_RUNNING="instsys"
for rpm in `find $BUILD_ROOT$TOPDIR/RPMS -type f -name "*.rpm"`; do
  case ${rpm##*/} in
    rpm-ndb-*) 
      echo "converting rpm database to ndb"
      chroot $BUILD_ROOT rpmdb --define '_db_backend ndb' --rebuilddb
      ;;
    bash-legacybin-*|glibc-legacylib-*)
      # skip those packages in case usrmerged system
      [ ! -L $BUILD_ROOT/bin ] || continue
      ;;
  esac
  RPM_FILE_LIST+=("$rpm")
done

ADDITIONAL_PARAMS=
test "$ABUILD_INIT_WITH_IGNORE_ARCH" = true && ADDITIONAL_PARAMS="$ADDITIONAL_PARAMS --ignorearch"

test -n "$(rpm --eval '%{?cross_sysroot}')" && {
  echo "skipping installation due to cross_sysroot being set."
  touch $BUILD_ROOT/skipped-install-cross
  exit 0
}

chroot $BUILD_ROOT rpm $ADDITIONAL_PARAMS --force --nodeps -Uv ${RPM_FILE_LIST[*]#$BUILD_ROOT} || {
    echo 'failed to install rpms, aborting build'
    test -n "$BUILD_ROOT" && touch $BUILD_ROOT/not-ready
    exit 1
}

