#!/bin/bash

echo "... testing for empty debuginfo packages"

fast=
test -x /usr/lib/rpm/rpmi && fast="--nodigest --nosignature"

RPMS=`find $BUILD_ROOT/usr/src/packages/RPMS -name "*-debuginfo-*.rpm" -o -name "*-debugsource-*.rpm"`
test -z "$RPMS" && exit 0
for rpm in $RPMS ; do
  HAS_DEBUG=
  HAS_SRC=
  for l in `rpm -qpl $fast "$rpm"` ; do
    case "$l" in
      /usr/lib/debug/*) HAS_DEBUG=true ;;
      /usr/src/debug/*) HAS_SRC=true ;;
    esac
  done
  if test -z "$HAS_DEBUG" -a -z "$HAS_SRC"; then
    echo '!'
    echo "!   $rpm: empty debuginfo/debugsource package, deleting"
    echo '!'
    rm -f "$rpm"
  fi
done
exit 0
