#!/bin/bash
# Check for dangerous compiler warnings
#

test "$AUTOBUILD" = "true" || LOGFILE=$BUILD_ROOT/.build.log

case $PNAME in
    kernel-*) exit 0 ;;
esac

if [ -f $LOGFILE ]; then

  echo "... testing for serious compiler warnings"
  echo "    (using /usr/lib/build/checks-data/check_gcc_output)"

  $BUILD_ROOT/usr/lib/build/checks-data/check_gcc_output $LOGFILE
  if [ $? -ne 0 ]; then
    exit 1;
  fi
fi

exit 0
