#!/bin/bash
# check if all directories are owned by a package

echo "... checking filelist"
ret=0

for pkg in `find $BUILD_ROOT/.build.packages/RPMS -name "*.rpm"`; do
	case "$pkg" in
		*-debuginfo-*|*-debugsource-*) continue ;;
	esac
	rpm -qlp $pkg | chroot $BUILD_ROOT /usr/lib/build/checks-data/checkdirs "${pkg##*/}"
	[ $? = 0 ] || ret=1
done

if [ "$ret" -ne 0 ]; then
	echo "*** This failure will be made fatal at Dec 8, please fix your package ***"
fi
#exit $ret
exit 0
