#!/bin/bash
# search for invalid requires.
#
export UNVALID_FILE_FOUND=false
TOPDIR=/usr/src/packages
test -d $BUILD_ROOT/.build.packages && TOPDIR=/.build.packages

FORBIDDEN_REQ=`find $BUILD_ROOT$TOPDIR/RPMS -name "*.rpm" | \
    xargs --no-run-if-empty rpm -qp --requires| \
    egrep "/usr/local/|/usr/share/bin"`

for LINE in $FORBIDDEN_REQ; do
        case "$LINE" in
          /usr/local/httpd/cgi-bin*)
            ;;
          *)
            echo \""$LINE"\" is not allowed as Requires.
            UNVALID_FILE_FOUND=true
          ;;
        esac
done

RPMLIST=`find $BUILD_ROOT$TOPDIR/RPMS -name "*.rpm"`
for pack in $RPMLIST ; do
	case $pack in
		*-debuginfo-*|*-debugsource-*)
			N=`rpm -qp --qf "%{NAME}" $pack`
			echo "dependency check for "`basename $pack`":"
			for i in `chroot $BUILD_ROOT rpm -qp --qf "[%{REQUIRENAME}\n]" ${pack##$BUILD_ROOT}` ; do
			    case $i in
				rpmlib*|*-debuginfo|*-debugsource) ;;
				*) chroot $BUILD_ROOT rpm -q --whatprovides $i || UNVALID_FILE_FOUND=true
				   ;;
			    esac
			done
			;;
		*) ;;
	esac
done
test $UNVALID_FILE_FOUND = true && exit 1

exit 0
