#!/bin/bash
# search for invalid requires.
#
export UNVALID_FILE_FOUND=false

for package in `find $BUILD_ROOT/usr/src/packages/RPMS -name "*.rpm"` ; do
  if rpm -qp --provides --nodigest --nosignature $package \
     | grep -q -E "^$(rpm -qp --nodigest --nosignature --queryformat='%{NAME}' $package)[[:space:]]*$"; then

    echo ""
    echo "ERROR: ${package##$BUILD_ROOT}"
    echo "       has an unversioned self-provide. "
    echo "       Remove it, self-provides are done automatically."
    echo "       If you don't understand this error message, contact dmueller@suse.de"
    echo ""
    UNVALID_FILE_FOUND=true
  fi
done

test $UNVALID_FILE_FOUND = true && exit 1

exit 0
