#!/bin/bash

echo "... testing for modified permissions"
TOPDIR=/usr/src/packages
test -d $BUILD_ROOT/.build.packages && TOPDIR=/.build.packages
test -f $BUILD_ROOT/etc/sysconfig/security || exit 0

HAD_ERRORS=0

RPM="chroot $BUILD_ROOT rpm --nodigest --nosignature -Vp --nofiledigest --nodeps"

for i in $(find $BUILD_ROOT$TOPDIR/RPMS -type f -name "*.rpm" | sort) ; do
    $RPM ${i#$BUILD_ROOT} > $BUILD_ROOT/.build_rpmVp_old
    sed -i.bak -e "s@^PERMISSION_SECURITY\(.*\)secure@PERMISSION_SECURITY\1easy@" \
	    $BUILD_ROOT/etc/sysconfig/security
    chroot $BUILD_ROOT /usr/bin/chkstat --system >/dev/null 2>&1
    $RPM ${i#$BUILD_ROOT} > $BUILD_ROOT/.build_rpmVp_new
    mv $BUILD_ROOT/etc/sysconfig/security.bak $BUILD_ROOT/etc/sysconfig/security
    chroot $BUILD_ROOT /usr/bin/chkstat --system >/dev/null 2>&1

    if ! cmp -s $BUILD_ROOT/.build_rpmVp_old $BUILD_ROOT/.build_rpmVp_new; then
	echo "--------------------------------------------------------------------"
	echo "package: $(rpm --nodigest --nosignature -qp --qf '%{NAME}' \"$i\")"
	echo "/usr/bin/chkstat modified files that are not properly handled!"
	echo "this will break rpm -V, ask ro for details."
	echo "diff for both runs of rpm -V:"
	diff -u0 "$BUILD_ROOT/.build_rpmVp_old" "$BUILD_ROOT/.build_rpmVp_new"
	echo "--------------------------------------------------------------------"
	HAD_ERRORS=1
    fi
done

rm -f $BUILD_ROOT/.build_rpmVp_old $BUILD_ROOT/.build_rpmVp_new

if test "$HAD_ERRORS" = 1 ; then
	touch $BUILD_ROOT/not-ready
	exit 1
fi
exit 0
